### ISSUE TITLE
Парсинг страниц в кодировке Windows-1251

### ISSUE THREAD

**Issue by vmaysov** [Imangazaliev/DiDOM#82]
При парсинге страницы с \<meta http-equiv="Content-Type" content="text/html; charset=windows-1251"\> вместо кириллицы выводятся пробелы. Адрес страницы: yaltakino.com/Spartak/schedule/

**Comment by nick-andren** [comment]
I think the problem is between PHP and the content rather than with this library in particular. For me, performing a file_get_contents() on the input and echoing it out results in bad characters being displayed without even touching this library.

I was able to recreate the issue with spaces using this code:
```
<?php

include 'vendor/autoload.php';

use DiDom\Document;

$document = new Document('http://yaltakino.com/Spartak/schedule/', true);

$posts = $document->find('.scheduleCaption');

foreach($posts as $post) {
    echo $post->text(), "\n";
}
```

This resulted in the issue described:
```
 
  
  
: 
 .  2
: 
  
: 
...
```

Not very much to look at :slightly_frowning_face: 

Loading the content and then converting the character set to UTF-8 makes it work, though:
```
<?php

include 'vendor/autoload.php';

use DiDom\Document;

$content = file_get_contents('http://yaltakino.com/Spartak/schedule/');

// Converting the content encoding to UTF-8 before loading it
$content = mb_convert_encoding($content, 'utf-8', 'windows-1251');
$document = new Document($content);

$posts = $document->find('.scheduleCaption');

foreach($posts as $post) {
    echo $post->text(), "\n";
}
```

This code above results in this output:
```
Название фильма
Меч Короля Артура
Трио В Перьях
Чужой: Завет
Стражи Галактики. Часть 2
Чужой: Завет
Меч Короля Артура
...
```

I hope this is an acceptable solution

**Comment by vmaysov** [comment]
@nick-andren yes, it work, thank you, but I thought could just set DiDom

**Comment by Imangazaliev** [comment]
The Document class accepts the third document - the document encoding:

```php
$url = 'http://yaltakino.com/Spartak/schedule/';

$document = new Document($url, true, 'windows-1251');

var_dump($document->first('.newsline')->html());
```

**Comment by vmaysov** [comment]
oh, tnx, it work!
